# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import run_recognition1

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 900)
        Form.setStyleSheet("background-image: url(:/backgruond/fingerprint-scan-logo-privacy-cyber-security-person-head-identity-information-and-network-protection-vector-icon-W36WKM.jpg);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 10, 631, 81))
        self.label.setStyleSheet("font: 30pt \"S Shell Dlg 2\";\n"
"\n"
"color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1000, 350, 151, 41))
        self.pushButton.setStyleSheet("\n"
"color:rgb(255, 255, 255);\n"
"background: gray;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"  \n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(950, 300, 241, 31))
        self.label_2.setStyleSheet("color:rgb(170, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1000, 480, 151, 41))
        self.pushButton_2.setStyleSheet("background:gray;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(940, 440, 241, 31))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(170, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(930, 570, 321, 31))
        self.label_4.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1000, 610, 151, 41))
        self.pushButton_3.setStyleSheet("background:gray;\n"
"color:rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(390, 680, 541, 121))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(40, 280, 256, 221))
        self.graphicsView.setObjectName("graphicsView")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(90, 230, 171, 41))
        self.label_6.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 540, 281, 41))
        self.label_7.setStyleSheet("color:rgb(170, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 590, 151, 41))
        self.pushButton_4.setStyleSheet("background: gray;\n"
"color:rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(490, 660, 291, 41))
        self.label_8.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(480, 709, 331, 151))
        self.lineEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);\n"
"background:gray;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(820, 830, 82, 25))
        self.pushButton_5.setStyleSheet("color:rgb(255, 255, 255);\n"
"background:blue;")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton_2.clicked.connect(run_recognition)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Criminal Face Detection System"))
        self.pushButton.setText(_translate("Form", "Upload "))
        self.label_2.setText(_translate("Form", "Upload Criminal Image"))
        self.pushButton_2.setText(_translate("Form", "Live Sream"))
        self.label_3.setText(_translate("Form", "Search in Live Stream"))
        self.label_4.setText(_translate("Form", "Search in Pre Recorded Video"))
        self.pushButton_3.setText(_translate("Form", "Recorded Video"))
        self.label_6.setText(_translate("Form", "Criminal Image"))
        self.label_7.setText(_translate("Form", "Check The Crminal Status"))
        self.pushButton_4.setText(_translate("Form", "Open"))
        self.label_8.setText(_translate("Form", "Description of the Criminal"))
        self.pushButton_5.setText(_translate("Form", "Submit"))
import background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
