# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QToolButton
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import sys
from PyQt5.QtWidgets import QToolButton, QLabel
from PyQt5.QtWidgets import QToolButton, QFileDialog

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 850)
        Form.setStyleSheet("background-image: url(:/backgruond/Downloads/Untitled6.png);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(460, 190, 311, 41))
        self.pushButton.setStyleSheet("\n"
"color:rgb(255, 255, 255);\n"
"background-image: url(:/backgruond/Downloads/Gradient Blue abstract background.jpg);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"  \n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(500, 150, 241, 31))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 450, 311, 41))
        self.pushButton_2.setStyleSheet("background-image: url(:/backgruond/Downloads/Gradient Blue abstract background.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(500, 410, 241, 31))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(460, 280, 321, 31))
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 320, 311, 41))
        self.pushButton_3.setStyleSheet("\n"
"color:rgb(255, 255, 255);\n"
"background-image: url(:/backgruond/Downloads/Gradient Blue abstract background.jpg);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        #self.graphicsView = QtWidgets.QGraphicsView(Form)
        #self.graphicsView.setGeometry(QtCore.QRect(30, 190, 271, 201))
        #self.graphicsView.setObjectName("graphicsView")
        #self.label_6 = QtWidgets.QLabel(Form)
        #self.label_6.setGeometry(QtCore.QRect(90, 140, 171, 41))
        #self.label_6.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        #self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 150, 281, 31))
        self.label_7.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 190, 271, 41))
        self.pushButton_4.setStyleSheet("background-image: url(:/backgruond/Downloads/Gradient Blue abstract background.jpg);\n"
"color:rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(240, 600, 291, 41))
        self.label_8.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(570, 780, 82, 25))
        self.pushButton_5.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"background:red;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 821, 91))
        self.label.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";\n"
"background:rgb(1, 57, 104);\n"
"\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(210, 640, 351, 171))
        self.plainTextEdit.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-image: url(:/backgruond/Downloads/Gradient Blue abstract background.jpg);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


        self.pushButton_2.clicked.connect(self.execute_main)
        self.pushButton.clicked.connect(self.execute_openregister)
        self.pushButton_3.clicked.connect(self.execute_prerecorded)
        self.pushButton_4.clicked.connect(self.execute_open)
        self.pushButton_5.clicked.connect(self.execute_opendeepai)

         # Create a "Sign Out" button and set its properties
        self.sign_out_button = QToolButton(Form)
        self.sign_out_button.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.sign_out_button.setIcon(QIcon("logout.jpg"))  # Set the path to your sign out icon
        self.sign_out_button.setIconSize(QtCore.QSize(24, 24))
        self.sign_out_button.setStyleSheet("background-color: rgb(1, 57, 104);")
        self.sign_out_button.clicked.connect(self.sign_out)



        # Create a label for "Log Out"
        self.log_out_label = QLabel(Form)
        self.log_out_label.setGeometry(QtCore.QRect(15, 60, 50, 20))
        self.log_out_label.setText("Log Out")
        self.log_out_label.setAlignment(QtCore.Qt.AlignCenter)
       # self.log_out_label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.log_out_label.setStyleSheet("background: rgb(1, 57, 104);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")

    def sign_out(self):
        Form.close()
        upload_process = subprocess.Popen([sys.executable, "loginGUI.py"])
        upload_process.wait()  # Wait for loginGUI.py to finish executing


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Register "))
        self.label_2.setText(_translate("Form", "Register New Criminal "))
        self.pushButton_2.setText(_translate("Form", "Live Sream"))
        self.label_3.setText(_translate("Form", "Search in Live Stream"))
        self.label_4.setText(_translate("Form", "Search in Pre Recorded Video"))
        self.pushButton_3.setText(_translate("Form", "Recorded Video"))
        #self.label_6.setText(_translate("Form", "Criminal Image"))
        self.label_7.setText(_translate("Form", "Check The Crminal Status"))
        self.pushButton_4.setText(_translate("Form", "Open"))
        self.label_8.setText(_translate("Form", "Description of the Criminal"))
        self.pushButton_5.setText(_translate("Form", "Submit"))
        self.label.setText(_translate("Form", "        Criminal Face Detection System"))


    def execute_main(self):
        gui_process = subprocess.Popen([sys.executable, "GUI.py"])
        main_process = subprocess.Popen([sys.executable, "main.py"])
        main_process.wait()  # Wait for main.py to finish executing
        gui_process.terminate()
        
    

    def execute_prerecorded(self):
        upload_process = subprocess.Popen([sys.executable, "search_in_prerecorded.py"])
        upload_process.wait()  # Wait for upload.py to finish executing 

    def execute_openregister(self):
        Form.close()
        upload_process = subprocess.Popen([sys.executable, "Register.py"])
        upload_process.wait()  
        

    def execute_open(self):     
        Form.close()
        upload_process = subprocess.Popen([sys.executable, "infoGUI.py"])
        upload_process.wait()  

    def execute_opendeepai(self):     
        Form.close()
        upload_process = subprocess.Popen([sys.executable, "DEEP_AI.py"])
        upload_process.wait()      
        


    
         
import background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()  
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

     
