# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
from PyQt5.QtWidgets import QToolButton
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QPushButton
from PyQt5 import QtCore, QtGui, QtWidgets
from mainGUItest import Ui_Form1
from PyQt5.QtWidgets import QToolButton, QFileDialog
import json
import sys
import os
import shutil
from PyQt5.QtWidgets import QApplication
import Register_rc

class Ui_Form4(object):
    def setupUi(self, Form):
        
        self.registrations = []
        Form.setObjectName("Form")
        Form.resize(1400, 850)
        Form.setStyleSheet("background-image: url(:/register/top desktop blue wallpapers blue wallpaper blue background hd 27jpg.jpg);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 80, 1221, 711))
        self.label.setStyleSheet("background: rgb(255, 255, 255);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(240, 240, 301, 301))
        self.graphicsView.setStyleSheet("background: url(:/register/Preson Logo3.png);\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(640, 230, 531, 41))
        self.lineEdit.setStyleSheet("background: rgb(87, 137, 172);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(640, 200, 201, 21))
        self.label_2.setStyleSheet("background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(640, 300, 201, 31))
        self.label_3.setStyleSheet("background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(640, 400, 201, 31))
        self.label_4.setStyleSheet("background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(640, 430, 531, 41))
        self.lineEdit_3.setStyleSheet("background: rgb(87, 137, 172);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(920, 330, 251, 41))
        self.comboBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(920, 300, 201, 31))
        self.label_5.setStyleSheet("background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(640, 330, 241, 41))
        self.dateEdit.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 560, 161, 41))
        self.pushButton.setStyleSheet("background: rgb(87, 137, 172);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(640, 510, 201, 31))
        self.label_6.setStyleSheet("background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(640, 540, 531, 41))
        self.lineEdit_4.setStyleSheet("background: rgb(87, 137, 172);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(640, 610, 201, 31))
        self.label_7.setStyleSheet("background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(640, 640, 531, 41))
        self.lineEdit_5.setStyleSheet("background: rgb(87, 137, 172);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(90, 50, 1221, 131))
        self.label_8.setStyleSheet("background-image: url(:/register/register.jpg);\n"
"\n"
"\n"
"font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 730, 151, 41))
        self.pushButton_2.setStyleSheet("background: rgb(249, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", " Full Name"))
        self.label_3.setText(_translate("Form", "Birthday"))
        self.label_4.setText(_translate("Form", "ID"))
        self.comboBox.setItemText(0, _translate("Form", "Male"))
        self.comboBox.setItemText(1, _translate("Form", "Female"))
        self.label_5.setText(_translate("Form", "Gender"))
        self.pushButton.setText(_translate("Form", "Upload Image"))
        self.label_6.setText(_translate("Form", "Phone Number"))
        self.label_7.setText(_translate("Form", "Address"))
        self.label_8.setText(_translate("Form", "                    Criminal Register"))
        self.pushButton_2.setText(_translate("Form", "Register"))



        
        self.pushButton.clicked.connect(self.execute_upload)
        self.pushButton_2.clicked.connect(self.save_registration_data)
        



    # Create a back button and set its properties
        self.back_button = QToolButton(Form)
        self.back_button.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.back_button.setIcon(QIcon("back.png"))  # Set the path to your back arrow icon
        self.back_button.setIconSize(QtCore.QSize(28, 28))
        self.back_button.setStyleSheet("background-color: white;")
        self.back_button.clicked.connect(self.go_to_GUI)
    


    

    def go_to_GUI(self):
        Form.close()
        upload_process = subprocess.Popen([sys.executable, "mainGUItest.py"])
        upload_process.wait()  # Wait for loginGUI.py to finish executing    


    def execute_upload(self):
      options = QFileDialog.Options()
      options |= QFileDialog.ReadOnly  # Make the file dialog read-only
      image_file, _ = QFileDialog.getOpenFileName(None, "Select an Image", "", "Images (*.png *.jpg *.jpeg *.bmp *.gif)", options=options)
    
      if image_file:
        self.uploaded_image = image_file  # Store the uploaded image filename
        pixmap = QtGui.QPixmap(image_file)
        scene = QtWidgets.QGraphicsScene()  # Create a QGraphicsScene

        # Set the pixmap to the exact size of the graphicsView
        pixmap = pixmap.scaled(self.graphicsView.width(), self.graphicsView.height())

        scene.addPixmap(pixmap)  # Add the pixmap to the scene
        self.graphicsView.setScene(scene)  # Set the scene in the graphicsView    

    def save_registration_data(self):
        full_name = self.lineEdit.text().strip()  # Get the full name from the lineEdit and remove leading/trailing spaces

        if not full_name:
            return  # Don't proceed if the full name is empty

        data = {
            "Full Name": full_name,
            "Birthday": self.dateEdit.date().toString(QtCore.Qt.ISODate),
            "ID": self.lineEdit_3.text(),
            "Gender": self.comboBox.currentText(),
            "Phone Number": self.lineEdit_4.text(),
            "Address": self.lineEdit_5.text(),
        }

        # Append the new data to the list
        self.registrations.append(data)

        # Copy the uploaded image to a specific folder and rename it to the full name
        if self.uploaded_image:
            image_filename = os.path.basename(self.uploaded_image)
            image_extension = os.path.splitext(image_filename)[-1]  # Get the file extension
            new_image_filename = f"{full_name}{image_extension}"  # New filename based on full name
            destination_folder = r'images'  # Change this to your desired folder path
            destination_path = os.path.join(destination_folder, new_image_filename)
            shutil.copy(self.uploaded_image, destination_path)
            data["Image Path"] = destination_path

        # Clear input fields
        self.clear_input_fields()

        # Save the data to the file
        self.save_to_file()  # Call the save_to_file method here





    def clear_input_fields(self):
        # Clear all input fields after registration
        self.lineEdit.clear()
        self.dateEdit.clear()
        self.lineEdit_3.clear()
        self.comboBox.setCurrentIndex(0)  # Reset gender to Male
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.graphicsView.setScene(None)  # Clear the image

    def save_to_file(self):
     if self.registrations:
        # Get the absolute path to the JSON file
        json_file_path = os.path.abspath('registration_data.json')

        existing_data = []  # To store existing data from the file

        # Check if the file already exists
        if os.path.exists(json_file_path):
            # Load existing data from the file
            with open(json_file_path, 'r') as json_file:
                existing_data = json.load(json_file)

        # Append the new data to the existing data
        existing_data.extend(self.registrations)

        # Create a new file or overwrite the existing one
        with open(json_file_path, 'w') as json_file:
            json.dump(existing_data, json_file, indent=4)

        # Clear the registrations list
        self.registrations.clear()
        print("Data saved to file:", json_file_path)
     else:
        print("No data to save.")



 

if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form4()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())



  