# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUP.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from loginGUI import Ui_Form
from PyQt5.QtWidgets import QToolButton
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QPushButton
from PyQt5 import QtCore, QtGui, QtWidgets
import Signup_rc
import hashlib
import subprocess
import sys
from PyQt5.QtWidgets import QProgressDialog


class Ui_Form3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1443, 850)
        Form.setStyleSheet("background-image: url(gradient-dark-blue-futuristic-digital-background.jpg);"
"")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(660, 40, 571, 771))
        self.label.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: rgb(0, 170, 250);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(700, 240, 231, 41))
        self.lineEdit.setStyleSheet("background: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(700, 170, 471, 31))
        self.label_2.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(106, 106, 106);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(700, 220, 91, 16))
        self.label_4.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(700, 360, 491, 41))
        self.lineEdit_2.setStyleSheet("background: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(700, 470, 491, 41))
        self.lineEdit_3.setStyleSheet("background: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(700, 330, 111, 21))
        self.label_5.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(700, 440, 91, 21))
        self.label_6.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(960, 240, 231, 41))
        self.lineEdit_4.setStyleSheet("background: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(960, 220, 91, 16))
        self.label_7.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(700, 580, 491, 41))
        self.lineEdit_5.setStyleSheet("background: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(700, 550, 151, 21))
        self.label_8.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(850, 670, 181, 51))
        self.pushButton.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background: rgb(0, 170, 250);")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(813, 750, 151, 20))
        self.label_9.setStyleSheet("background: rgb(255, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(230, 190, 431, 491))
        self.label_10.setStyleSheet("background: url(:/signup/Screenshot 2023-08-26 195347.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(230, 600, 431, 211))
        self.label_11.setStyleSheet("background: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(230, 40, 431, 151))
        self.label_12.setStyleSheet("background: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(230, 130, 1001, 16))
        self.line.setStyleSheet("background: rgb(0, 170, 250);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 1001, 91))
        self.label_3.setStyleSheet("background: rgb(0, 170, 250);\n"
"color: rgb(255, 255, 255);\n"
"font: 81 44pt \"Rockwell Extra Bold\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(960, 750, 61, 21))
        self.pushButton_2.setStyleSheet("background: rgb(0, 170, 250);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_2.clicked.connect(self.execute_open)
        self.lineEdit.returnPressed.connect(self.sign_up)
        self.lineEdit_2.returnPressed.connect(self.sign_up)
        self.lineEdit_3.returnPressed.connect(self.sign_up)
        self.lineEdit_4.returnPressed.connect(self.sign_up)
        self.lineEdit_5.returnPressed.connect(self.sign_up)
        self.pushButton.clicked.connect(self.sign_up)
        

        # Set password masking for lineEdit_3 and lineEdit_4
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)


        #Create a back button and set its properties
        self.back_button = QToolButton(Form)
        self.back_button.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.back_button.setIcon(QIcon(r"back.png"))  # Set the path to your back arrow icon
        self.back_button.setIconSize(QtCore.QSize(28, 28))
        self.back_button.setStyleSheet("background-color: white;")
        self.back_button.clicked.connect(self.go_to_login)
        


    def go_to_login(self):
        Form.close()
        upload_process = subprocess.Popen([sys.executable, "loginGUI.py"])
        upload_process.wait()  # Wait for loginGUI.py to finish executing

   

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Please fill in this form to create an account!"))
        self.label_4.setText(_translate("Form", "First Name"))
        self.label_5.setText(_translate("Form", "Employee ID"))
        self.label_6.setText(_translate("Form", "Password"))
        self.label_7.setText(_translate("Form", "Last Name"))
        self.label_8.setText(_translate("Form", "Confirm Password"))
        self.pushButton.setText(_translate("Form", "Sign Up"))
        self.label_9.setText(_translate("Form", "Already have an account?"))
        self.label_3.setText(_translate("Form", "                       Sign Up"))
        self.pushButton_2.setText(_translate("Form", "Log in"))
        
        

    def sign_up(self):
        first_name = self.lineEdit.text()
        employee_id = self.lineEdit_2.text()
        password = self.lineEdit_3.text()  # Get password from lineEdit_3
        last_name = self.lineEdit_4.text()
        confirm_password = self.lineEdit_5.text()  # Get confirm password from lineEdit_4
        

        if not employee_id or not password or not confirm_password or not first_name or not last_name:
            QtWidgets.QMessageBox.critical(Form, "Error", "All fields are required.")
            return

        if password != confirm_password:
            QtWidgets.QMessageBox.critical(Form, "Error", "Passwords do not match.")
            return
        

        # Read existing IDs from the file
        existing_ids = []
        try:
            with open("Employee_ID.txt", "r") as file:
                existing_ids = [line.strip() for line in file.readlines()]
        except FileNotFoundError:
            pass

        if employee_id not in existing_ids:
            QtWidgets.QMessageBox.critical(Form, "Error", "Employee ID not found.")
            return

        

        # Hash the password
        hashed_password = hashlib.sha256(password.encode('utf-8')).hexdigest()

        # Save the ID and hashed password in a file
        try:
            with open("Employee_Passwords.txt", "a") as file:
                file.write(f"{employee_id} {hashed_password}\n")
            QtWidgets.QMessageBox.information(Form, "Success", "Account created successfully.")
        except Exception as e:
            QtWidgets.QMessageBox.critical(Form, "Error", f"An error occurred: {str(e)}")



    def show_waiting_message(self):
        self.progressDialog = QProgressDialog("login...", None, 0, 0)
        self.progressDialog.setWindowModality(QtCore.Qt.WindowModal)
        self.progressDialog.setWindowTitle("Please Wait")
        self.progressDialog.setCancelButton(None)
        self.progressDialog.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)
        self.progressDialog.setWindowIcon(QtGui.QIcon())
        self.progressDialog.setAutoClose(True) 
        self.progressDialog.show()
        Form.close()


    def execute_open(self):
        self.show_waiting_message()
        upload_process = subprocess.Popen([sys.executable, "loginGUI.py"])
        upload_process.wait()  # Wait for upload.py to finish executing
        self.progressDialog.close() 

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form3()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())